### ISSUE TITLE
IllegalArgumentException: URI is not absolute when using external schemas

### ISSUE THREAD

**Issue by ddossot** [mulesoft-labs/raml-java-client-generator#2]
My RAML contains pretty standard references to external schemas, like:
```yaml
schema:
    - error: !include schema/error.js
```
I'm using the latest `0.1-SNAPSHOT` of the Maven plug-in, configured with:
```xml
<ramlURL>${project.baseUri}/src/main/resources/spec/api.raml</ramlURL>
```
I'm receiving this exception during codegen:
<pre>
java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:65)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:47)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:93)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:74)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:41)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:60)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:31)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:122)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:66)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:88)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:38)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.mule.client.codegen.RamlJavaClientGenerator.generatePojoFromSchema(RamlJavaClientGenerator.java:417)
	at org.mule.client.codegen.RamlJavaClientGenerator.generate(RamlJavaClientGenerator.java:96)
	at org.mule.client.codegen.RamlJavaClientGenerator.generate(RamlJavaClientGenerator.java:86)
	at org.mule.client.codegen.maven.plugin.RamlJavaClientGeneratorMojo.execute(RamlJavaClientGeneratorMojo.java:61)
</pre>

**Comment by machaval** [comment]
Hi David, Thanks for reporting the Issue. Do you have the error.js so that I can take a look at it.

**Comment by ddossot** [comment]
Here you go:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": 
    {
        "message": 
        {
            "type": "string"
        }
    },

    "required": 
    [
        "message"
    ],

    "additionalProperties": false
}
```
