### ISSUE TITLE
NPE when full path defined twice

### ISSUE THREAD

**Issue by ktmcgrat** [mulesoft-labs/raml-java-client-generator#23]
The following raml

#%RAML 1.0
title: test
version: v1

/api/a:
    get:
/api/b:
    get:

Will cause the following error to be thrown.

java.lang.NullPointerException
	at org.mule.client.codegen.RamlJavaClientGenerator.buildResourceClass(RamlJavaClientGenerator.java:277)
	at org.mule.client.codegen.RamlJavaClientGenerator.generate(RamlJavaClientGenerator.java:191)
	at org.mule.client.codegen.RamlJavaClientGenerator.generate(RamlJavaClientGenerator.java:90)
	at BuildJarFromRAML.main(BuildJarFromRAML.java:33)

Because the /api path is defined twice, when processing /api/b the parent of b is not linked correctly as it knows /api already exists but doesn't set it's parent properly.

**Comment by ullgren** [comment]
I belive this issue was fixed PR #34.

**Comment by machaval** [comment]
Works for me
