### ISSUE TITLE
Getting StackOverflowError when RAML contains trees/cycle dependencies for optional children

### ISSUE THREAD

**Issue by etsybaev** [mulesoft-labs/raml-java-client-generator#26]
The 'org.mule.raml.codegen', name: 'raml-client-generator-core', version: '0.2' plugin retrieves StackOverflowError when generating POJO if raml contains  trees/cycle dependencies for optional children

**To Reproduce**
1. Put this raml to your project:
"
#%RAML 1.0
title: locations
version: 1.0.0
baseUri: /bar/locations
protocols: [ HTTPS ]
mediaType: application/json
documentation:
  - title: Some title
    content:
      'Blah-blah-blah.'
types:
  **foo**:
    type: object
    description: Some definition
    properties:
      children?:
        description: The list of children nodes.
        **type: foo[]**
/bar:
  get:
    displayName: SomeDisplayNameValue
    description: SomeDescriptionValue
    responses:
      200:
        body:
          application/json:
            type: foo
"

2. Try to generate POJO using  'org.mule.raml.codegen', name: 'raml-client-generator-core', version: '0.2' plugin

3. See error:

Exception in thread "main" java.lang.StackOverflowError
	at com.sun.codemodel.JPackage._class(JPackage.java:177)
	at com.sun.codemodel.JPackage._class(JPackage.java:164)
	at com.sun.codemodel.JPackage._class(JPackage.java:197)
	at org.jsonschema2pojo.rules.ObjectRule.makeUnique(ObjectRule.java:631)
	at org.jsonschema2pojo.rules.ObjectRule.makeUnique(ObjectRule.java:635)
        ...
        at org.jsonschema2pojo.rules.ObjectRule.makeUnique(ObjectRule.java:635)
	at org.jsonschema2pojo.rules.ObjectRule.makeUnique(ObjectRule.java:635)
	at org.jsonschema2pojo.rules.ObjectRule.getClassName(ObjectRule.java:613)
	at org.jsonschema2pojo.rules.ObjectRule.createClass(ObjectRule.java:306)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:98)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:81)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:37)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:113)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
        ....
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:113)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:70)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:38)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:119)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)

**Expected behavior**
POJO files must be generated

**Comment by etsybaev** [comment]
It seems like the problem is on RamlJavaClientgenerator class generatePojoFromSchema.

Probably jsonschema2pojo lib that you use has an issue. If you pass json as URL resource -it works fine, but it fails if you pass json as a String

**Comment by markwimpory** [comment]
This is pretty bad and needs fixing asap.
