### ISSUE TITLE
MessageBodyReader not found for media type=text/plain

### ISSUE THREAD

**Issue by s2tu** [mulesoft-labs/raml-java-client-generator#9]
I used the raml-java-client-generator to generate jars for MashapeWeatherAPIClient which are later put in my Java project.   When i try to run my java project I get an error.  Can someone help me solve this?

`package com.newpackage;

import org.mule.example.api.MashapeWeatherAPIClient;
import org.mule.example.resource.weatherdata.model.WeatherdataGETHeader;
import org.mule.example.resource.weatherdata.model.WeatherdataGETQueryParam;

public class TheMain {
	public static void main(String[] args){
		WeatherdataGETHeader header = new WeatherdataGETHeader();
		header.setXMashapeKey("g9zsZDIplfmshIOO3pNVkHjHn1Kep13OsF3jsn4bVomnkRBy5x");
		WeatherdataGETQueryParam queryParams = new WeatherdataGETQueryParam( -121.955236, 37.354108);
		
		MashapeWeatherAPIClient.create().weatherdata.get(queryParams, header);
	}
}
`

My error is 

Exception in thread "main" org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain, type=class org.mule.example.resource.weatherdata.model.WeatherdataGETResponse, genericType=class org.mule.example.resource.weatherdata.model.WeatherdataGETResponse.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:232)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:785)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:111)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:108)
	at org.mule.example.resource.weatherdata.Weatherdata.get(Weatherdata.java:52)
	at com.newpackage.TheMain.main(TheMain.java:13)

**Comment by machaval** [comment]
Hi can you please attach the raml

**Comment by rscadrde** [comment]
Problem is probably that a few lines above 
`Weatherdata.java:52`
the generated source shows
`target.request(MediaType.APPLICATION_JSON_TYPE);`
is requested always (should generate to `TEXT_PLAIN_TYPE`)

**Comment by rscadrde** [comment]
changing

`        final JVar invocationBuilder = body.decl(JMod.FINAL, cm.ref(Invocation.Builder.class), "invocationBuilder", targetVal.invoke("request").arg(cm.directClass(MediaType.class.getName()).staticRef("APPLICATION_JSON_TYPE")));
`

to

```
        // for compatibility to 0.1.1 version: default is json
        String tempMediaTypeRef = "APPLICATION_JSON_TYPE";
        if (returnType.equals(cm.ref(String.class))) {
        	tempMediaTypeRef = "TEXT_PLAIN_TYPE";
        }
		final JVar invocationBuilder = body.decl(JMod.FINAL, cm.ref(Invocation.Builder.class), "invocationBuilder", targetVal.invoke("request").arg(cm.directClass(MediaType.class.getName()).staticRef(tempMediaTypeRef)));

```
helps for this case but fails in case of json body without entities (e.g. global-type-body )

see commit 
https://github.com/rscadrde/raml-java-client-generator/commit/b62f09e18cfaa1190e751fe69d5dcaa3c192afe1

Looks like method signatures for 
`org.mule.client.codegen.RamlJavaClientGenerator.buildReturnType(JCodeModel, ActionType, Response, String, String)`
needs to be changed to return a container with JType and the corresponding mimeType and then that mimeType passed to "request" in `org.mule.client.codegen.clientgenerator.Jersey2RestClientGeneratorImpl.callHttpMethod(JCodeModel, JDefinedClass, JType, JBodyType, JType, JType, Action, ApiModel)`
